import '@/globals.css'
import { Noto_Sans_JP } from '@next/font/google'

const notoSansJp = Noto_Sans_JP({ weight: '400' })

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="ja" className={notoSansJp.className}>
      <head>
        <title>NEXT JS 13 Sample</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>{children}</body>
    </html>
  )
}

export default RootLayout
